# Generated by Django 3.1 on 2020-08-20 14:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_de',
            field=wagtail.core.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_es',
            field=wagtail.core.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_fr',
            field=wagtail.core.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_it',
            field=wagtail.core.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
